apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myfeeder.fullname" . }}-config
  labels:
    {{- include "myfeeder.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.externalPostgres.host }}:{{ .Values.externalPostgres.port }}/{{ .Values.externalPostgres.database }}"
  SPRING_DATA_REDIS_HOST: "{{ include "myfeeder.fullname" . }}-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  {{- if .Values.spring.profiles }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles | quote }}
  {{- end }}
