apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myfeeder.fullname" . }}-secret
  labels:
    {{- include "myfeeder.labels" . | nindent 4 }}
type: Opaque
stringData:
  spring-datasource-username: {{ .Values.externalPostgres.username | quote }}
  spring-datasource-password: {{ .Values.secrets.postgresPassword | quote }}
  spring-ai-anthropic-api-key: {{ .Values.secrets.anthropicApiKey | quote }}
  myfeeder-raindrop-api-token: {{ .Values.secrets.raindropApiToken | quote }}
{{- if .Values.secrets.googleApplicationCredentials }}
data:
  gcp-credentials.json: {{ .Values.secrets.googleApplicationCredentials | quote }}
{{- end }}
