apiVersion: v1
kind: Service
metadata:
  name: {{ include "myfeeder.fullname" . }}
  labels:
    {{- include "myfeeder.labels" . | nindent 4 }}
    {{- include "myfeeder.appSelectorLabels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "myfeeder.appSelectorLabels" . | nindent 4 }}
