apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "myfeeder.fullname" . }}-postgres
  labels:
    {{- include "myfeeder.labels" . | nindent 4 }}
    {{- include "myfeeder.postgresSelectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
