apiVersion: v1
kind: Service
metadata:
  name: {{ include "myfeeder.fullname" . }}-postgres
  labels:
    {{- include "myfeeder.labels" . | nindent 4 }}
    {{- include "myfeeder.postgresSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "myfeeder.postgresSelectorLabels" . | nindent 4 }}
