export interface Theme {
  id: string
  name: string
  type: 'dark' | 'light'
  vars: Record<string, string>
}

export const themes: Record<string, Theme> = {
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    type: 'dark',
    vars: {
      '--bg-primary': '#0f0f1a',
      '--bg-secondary': '#1a1a2e',
      '--bg-tertiary': '#16213e',
      '--bg-active': '#0f3460',
      '--text-primary': '#eee',
      '--text-secondary': '#aaa',
      '--text-muted': '#666',
      '--accent': '#6c63ff',
      '--border': '#333',
      '--hover-bg': 'rgba(108, 99, 255, 0.15)',
      '--toast-error-bg': '#3d1515',
      '--toast-error-text': '#e74c3c',
      '--toast-success-bg': '#153d1a',
      '--toast-success-text': '#2ecc71',
      '--accent-text': '#ffffff',
    },
  },
  'solarized-dark': {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    vars: {
      '--bg-primary': '#002b36',
      '--bg-secondary': '#073642',
      '--bg-tertiary': '#073642',
      '--bg-active': '#003847',
      '--text-primary': '#fdf6e3',
      '--text-secondary': '#93a1a1',
      '--text-muted': '#657b83',
      '--accent': '#b58900',
      '--border': '#586e75',
      '--hover-bg': 'rgba(181, 137, 0, 0.15)',
      '--toast-error-bg': '#3d1515',
      '--toast-error-text': '#dc322f',
      '--toast-success-bg': '#153d1a',
      '--toast-success-text': '#859900',
      '--accent-text': '#fdf6e3',
    },
  },
  'solarized-light': {
    id: 'solarized-light',
    name: 'Solarized Light',
    type: 'light',
    vars: {
      '--bg-primary': '#fdf6e3',
      '--bg-secondary': '#eee8d5',
      '--bg-tertiary': '#eee8d5',
      '--bg-active': '#fdf6e3',
      '--text-primary': '#073642',
      '--text-secondary': '#586e75',
      '--text-muted': '#93a1a1',
      '--accent': '#268bd2',
      '--border': '#d3cbb7',
      '--hover-bg': 'rgba(38, 139, 210, 0.12)',
      '--toast-error-bg': '#fde8e8',
      '--toast-error-text': '#dc322f',
      '--toast-success-bg': '#e8fde8',
      '--toast-success-text': '#859900',
      '--accent-text': '#fdf6e3',
    },
  },
  'sky-blue': {
    id: 'sky-blue',
    name: 'Sky Blue',
    type: 'light',
    vars: {
      '--bg-primary': '#eceff1',
      '--bg-secondary': '#e3e8ec',
      '--bg-tertiary': '#e8ecf0',
      '--bg-active': '#f5f7fa',
      '--text-primary': '#263238',
      '--text-secondary': '#546e7a',
      '--text-muted': '#90a4ae',
      '--accent': '#1976d2',
      '--border': '#cfd8dc',
      '--hover-bg': 'rgba(25, 118, 210, 0.1)',
      '--toast-error-bg': '#fde8e8',
      '--toast-error-text': '#d32f2f',
      '--toast-success-bg': '#e8fde8',
      '--toast-success-text': '#388e3c',
      '--accent-text': '#ffffff',
    },
  },
  light: {
    id: 'light',
    name: 'Light',
    type: 'light',
    vars: {
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#f8f9fa',
      '--bg-tertiary': '#f1f3f5',
      '--bg-active': '#ffffff',
      '--text-primary': '#1a1a1a',
      '--text-secondary': '#495057',
      '--text-muted': '#adb5bd',
      '--accent': '#6366f1',
      '--border': '#dee2e6',
      '--hover-bg': 'rgba(99, 102, 241, 0.08)',
      '--toast-error-bg': '#fde8e8',
      '--toast-error-text': '#e53e3e',
      '--toast-success-bg': '#e8fde8',
      '--toast-success-text': '#38a169',
      '--accent-text': '#ffffff',
    },
  },
  nord: {
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    vars: {
      '--bg-primary': '#2e3440',
      '--bg-secondary': '#3b4252',
      '--bg-tertiary': '#3b4252',
      '--bg-active': '#434c5e',
      '--text-primary': '#eceff4',
      '--text-secondary': '#d8dee9',
      '--text-muted': '#7b88a1',
      '--accent': '#88c0d0',
      '--border': '#4c566a',
      '--hover-bg': 'rgba(136, 192, 208, 0.15)',
      '--toast-error-bg': '#3d1515',
      '--toast-error-text': '#bf616a',
      '--toast-success-bg': '#153d1a',
      '--toast-success-text': '#a3be8c',
      '--accent-text': '#2e3440',
    },
  },
}

export const themeList = Object.values(themes)
