nameOverride: ""
fullnameOverride: ""

app:
  image:
    repository: gitea.bartram.org:3000/bartram/myfeeder
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  service:
    type: LoadBalancer
    port: 8080
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.44.204"
  resources: {}
  replicaCount: 1

externalPostgres:
  host: pg.bartram.org
  port: 5432
  database: myfeeder
  username: myfeeder

redis:
  image:
    repository: redis
    tag: "7"

spring:
  profiles: ""

secrets:
  postgresPassword: ""
  anthropicApiKey: ""
  googleApplicationCredentials: ""
